package com;

import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Kevin.ONeal' at '1/16/15 1:42 PM' with Gradle 2.1
 *
 * @author Kevin.ONeal, @date 1/16/15 1:42 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    	Library library = new Library();
    	library.someLibraryMethod();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
