package com;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kevin.ONeal' at '1/16/15 1:42 PM' with Gradle 2.1
 *
 * @author Kevin.ONeal, @date 1/16/15 1:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("in consumer");
    	Producer producer = new Producer();
    	System.out.println("before called to producer ");
    	producer.someLibraryMethod();
    	System.out.println("after called to producer ");
        return true;
    }
}
